# Generated by Django 3.1.2 on 2020-10-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='test_field',
            field=models.TextField(blank=True),
        ),
    ]
